### ISSUE TITLE
Homepage taking too long to load

### ISSUE THREAD

**Issue by riverspirit** [MozillaKerala/MKO#4]
Home page is taking too long to load. The [logo image](http://dev.nikz.in/images/main-logo.png) is too large. It should be resized to the the correct dimension to be used in the page.

**Comment by riverspirit** [comment]
Also probably all other resources should be optimized. Use something like [YSlow](http://yslow.org/) to see where things can be improved.

**Comment by nikhiljohn10** [comment]
@riverspirit  Loading time have been improved under production env. of sails framework. Also I have removed external link to various image file and optimized it inside the framework itself.

**Comment by riverspirit** [comment]
:+1:
